### ISSUE TITLE
Access global objects from Python

### ISSUE THREAD

**Issue by corndog2000** [404background/node-red-contrib-python-venv#35]
I know that currently you can access the node-red msg object from the python code. I was wonder what it would take to read/write to node-red global variables too.

**Comment by 404background** [comment]
Thank you @corndog2000 for your comments on the issue!

For now, only the msg object can be accessed from the node.
Access to msg objects was implemented in #6 .
The following is implemented in node/venv.js as an argument when executing Python.
```
const message = Buffer.from(JSON.stringify(msg)).toString('base64')
const args = [
  '-c',
  `import base64;import json;msg=json.loads(base64.b64decode(r'${message}').decode('utf-8'));exec(open(r'${filePath}', encoding='utf-8').read())`,
]
```

It would be more convenient for future use to be able to access flow and global objects as well.
I will try to implement that.

**Comment by 404background** [comment]
@corndog2000 
In #42 , I have implemented access to flow and global variables.
Because “global” is a reserved word in Python, I implemented it to be handled as follows.
![image](https://github.com/user-attachments/assets/993c9444-5db3-46cb-a05b-5fb0d7bfba31)

I will also consider how to implement #36 .

**Comment by corndog2000** [comment]
Awesome! Thank you so much! ❤️
